---
#
# Ansible managed
#
repository:
  description: Install qemu.
  homepage: https://robertdebock.nl/
  topics: adauth, activedirectory, authentication, ansible, molecule, tox, playbook, hacktoberfest
