---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: test qemu-kvm
      command: qemu-kvm --version
      environment:
        PATH: "/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec"
