---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    _qemu_verify_command:
      default: qemu-kvm
      Alpine: qemu-system-x86_64
      Debian: qemu-system-x86_64
    qemu_verify_command: "{{ _qemu_verify_command[ansible_os_family] | default(_qemu_verify_command['default']) }}"

  tasks:
    - name: test qemu-kvm
      command: "{{ qemu_verify_command }} --version"
      environment:
        PATH: "/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec"
